### ISSUE TITLE
Can't launch python -m secure_cartography.scart

### ISSUE THREAD

**Issue by yoanDacosta** [scottpeterman/secure_cartography#1]
I haved  follow instruction in the readme but, i can't used the program

`secure_cartography on 🌱 main via 🐍 v3.10.12 (.mapvenv) took 3m13s 
❯ python -m secure_cartography.scart
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/test/secure_cartography/secure_cartography/scart.py", line 14, in <module>
    import credslib
ModuleNotFoundError: No module named 'credslib'`

**Comment by scottpeterman** [comment]
I just pushed an update that fixed some setup issues, and now you can install via pip!   Pip install secure-cartography. Let me know if that doesn't clear things up.
